name: Lint

on:
  push:
  pull_request:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:coverage

      - name: Coverage
        if: ${{ steps.install.conclusion == 'success' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          vite-config-path: vitest.config.unit.ts